stages:
  - deploy

variables:
  DOCKER_TAG: java.ci.cd.image

package:
  stage: deploy
  tags:
    - docker
    - docker_artifactory
    - docker_gcr
  script:
    - docker build -t artifactory-gojek.golabs.io:6555/cx-docker-package:latest .
    - docker push artifactory-gojek.golabs.io:6555/cx-docker-package:latest
  only:
    - master

