stages:
  - build_and_push_to_registry

docker-build-and-push:
  stage: build_and_push_to_registry
  script:
    - docker build -t artifactory-gojek.golabs.io:6555/cx-docker-package:latest -t asia.gcr.io/systems-0001/cx-docker-package:latest -f Dockerfile .
    - docker push artifactory-gojek.golabs.io:6555/cx-docker-package:latest
    - docker push asia.gcr.io/systems-0001/cx-docker-package:latest
  tags:
    - docker_artifactory
    - docker_gcr
